// Package admin provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package admin

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BasicAuthScopes = "BasicAuth.Scopes"
)

// Defines values for CacheDependencyCheckStatus.
const (
	CacheDependencyCheckStatusDegraded CacheDependencyCheckStatus = "degraded"
	CacheDependencyCheckStatusDown     CacheDependencyCheckStatus = "down"
	CacheDependencyCheckStatusUnknown  CacheDependencyCheckStatus = "unknown"
	CacheDependencyCheckStatusUp       CacheDependencyCheckStatus = "up"
)

// Defines values for CacheHealthStatus.
const (
	Healthy     CacheHealthStatus = "healthy"
	Unavailable CacheHealthStatus = "unavailable"
	Unhealthy   CacheHealthStatus = "unhealthy"
)

// Defines values for DependencyCheckStatus.
const (
	DependencyCheckStatusDegraded DependencyCheckStatus = "degraded"
	DependencyCheckStatusDown     DependencyCheckStatus = "down"
	DependencyCheckStatusUnknown  DependencyCheckStatus = "unknown"
	DependencyCheckStatusUp       DependencyCheckStatus = "up"
)

// Defines values for DeviceState.
const (
	Available DeviceState = "available"
	InUse     DeviceState = "in-use"
	Inactive  DeviceState = "inactive"
)

// Defines values for HealthStatus.
const (
	HealthStatusDegraded    HealthStatus = "degraded"
	HealthStatusDown        HealthStatus = "down"
	HealthStatusMaintenance HealthStatus = "maintenance"
	HealthStatusOk          HealthStatus = "ok"
)

// Defines values for LivenessStatus.
const (
	LivenessStatusDegraded    LivenessStatus = "degraded"
	LivenessStatusDown        LivenessStatus = "down"
	LivenessStatusMaintenance LivenessStatus = "maintenance"
	LivenessStatusOk          LivenessStatus = "ok"
)

// Defines values for MetaApiVersion.
const (
	MetaApiVersionV1 MetaApiVersion = "v1"
)

// Defines values for ReadinessStatus.
const (
	Degraded    ReadinessStatus = "degraded"
	Down        ReadinessStatus = "down"
	Maintenance ReadinessStatus = "maintenance"
	Ok          ReadinessStatus = "ok"
)

// Defines values for ApiVersionHeader.
const (
	ApiVersionHeaderV1 ApiVersionHeader = "v1"
)

// CacheDependencyCheck defines model for CacheDependencyCheck.
type CacheDependencyCheck struct {
	// Details Cache-specific details
	Details *struct {
		// PoolStats Connection pool statistics
		PoolStats *PoolStats `json:"poolStats,omitempty"`

		// TotalKeys Total number of keys in the cache
		TotalKeys *int `json:"totalKeys,omitempty"`
	} `json:"details,omitempty"`

	// Error Error message if the dependency is unhealthy
	Error *string `json:"error,omitempty"`

	// LastChecked Timestamp of the last health check for this dependency
	LastChecked *time.Time `json:"lastChecked,omitempty"`

	// LatencyMs Latency of the last health check in milliseconds
	LatencyMs *int `json:"latencyMs,omitempty"`

	// Message Additional information about the dependency status
	Message *string `json:"message,omitempty"`

	// Status The status of the dependency
	Status CacheDependencyCheckStatus `json:"status"`
}

// CacheDependencyCheckStatus The status of the dependency
type CacheDependencyCheckStatus string

// CacheError Error response for cache operations
type CacheError struct {
	// Error Error message describing the failure
	Error string `json:"error"`
}

// CacheHealth Cache health status response
type CacheHealth struct {
	// Error Error message if cache is unavailable
	Error *string `json:"error,omitempty"`

	// Status Current health status of the cache
	Status CacheHealthStatus `json:"status"`
}

// CacheHealthStatus Current health status of the cache
type CacheHealthStatus string

// CachePatternPurge Response after purging cache entries by pattern
type CachePatternPurge struct {
	// Deleted Number of cache entries deleted
	Deleted int64 `json:"deleted"`

	// Pattern The pattern that was used for purging
	Pattern string `json:"pattern"`

	// Status Result message of the purge operation
	Status string `json:"status"`
}

// CachePurge Response after purging cache entries
type CachePurge struct {
	// Id Device ID that was purged (only for single device purge)
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Status Result message of the purge operation
	Status string `json:"status"`
}

// CreateDevice Request body for creating a new device
type CreateDevice struct {
	// Brand The brand/manufacturer of the device
	Brand string `json:"brand"`

	// Name The name of the device
	Name string `json:"name"`

	// State The current state of the device
	State *DeviceState `json:"state,omitempty"`
}

// DependencyCheck Status of a single dependency
type DependencyCheck struct {
	// Details Additional dependency-specific details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Error message if the dependency is unhealthy
	Error *string `json:"error,omitempty"`

	// LastChecked Timestamp of the last health check for this dependency
	LastChecked *time.Time `json:"lastChecked,omitempty"`

	// LatencyMs Latency of the last health check in milliseconds
	LatencyMs *int `json:"latencyMs,omitempty"`

	// Message Additional information about the dependency status
	Message *string `json:"message,omitempty"`

	// Status The status of the dependency
	Status DependencyCheckStatus `json:"status"`
}

// DependencyCheckStatus The status of the dependency
type DependencyCheckStatus string

// Device A device resource
type Device struct {
	// Brand The brand/manufacturer of the device
	Brand string `json:"brand"`

	// CreatedAt Timestamp when the device was created (immutable)
	CreatedAt time.Time `json:"createdAt"`

	// Id Unique identifier for the device (UUID v7)
	Id openapi_types.UUID `json:"id"`

	// Links HATEOAS links for device navigation
	Links *DeviceLinks `json:"links,omitempty"`

	// Name The name of the device
	Name string `json:"name"`

	// State The current state of the device
	State DeviceState `json:"state"`

	// UpdatedAt Timestamp when the device was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// DeviceEnvelope Response envelope containing a single device with metadata
type DeviceEnvelope struct {
	// Data A device resource
	Data Device `json:"data"`

	// Meta Response metadata containing tracing information and API versioning.
	// All successful responses include this field to support observability and debugging.
	Meta Meta `json:"meta"`
}

// DeviceLinks HATEOAS links for device navigation
type DeviceLinks struct {
	// Self Link to this device resource
	Self *string `json:"self,omitempty"`
}

// DeviceState The current state of the device
type DeviceState string

// DevicesListEnvelope Response envelope containing a paginated list of devices with metadata
type DevicesListEnvelope struct {
	// Data List of devices
	Data []Device `json:"data"`

	// Meta Response metadata containing tracing information and API versioning.
	// All successful responses include this field to support observability and debugging.
	Meta Meta `json:"meta"`

	// Pagination Pagination metadata for list responses
	Pagination Pagination `json:"pagination"`
}

// Error Standard error response format
type Error struct {
	// Code Machine-readable error code
	Code string `json:"code"`

	// Details Additional error details for validation errors
	Details *[]ErrorDetail `json:"details,omitempty"`

	// Message Human-readable error message
	Message string `json:"message"`

	// RequestId Unique request identifier for tracing
	RequestId openapi_types.UUID `json:"requestId"`

	// Timestamp Timestamp when the error occurred
	Timestamp time.Time `json:"timestamp"`

	// TraceId W3C Trace Context trace ID for distributed tracing (from traceparent header)
	TraceId *string `json:"traceId,omitempty"`
}

// ErrorDetail Detailed information about a specific error
type ErrorDetail struct {
	// Code Machine-readable error code for this specific error
	Code *string `json:"code,omitempty"`

	// Field The field that caused the error
	Field string `json:"field"`

	// Message Description of what is wrong with the field
	Message string `json:"message"`
}

// Health Comprehensive health check response with system metrics
type Health struct {
	// Checks Status of individual dependency checks grouped by category
	Checks struct {
		// Infra Infrastructure dependencies (storage, cache, etc.)
		Infra struct {
			Cache *CacheDependencyCheck `json:"cache,omitempty"`

			// Storage Status of a single dependency
			Storage DependencyCheck `json:"storage"`
		} `json:"infra"`

		// Services Service dependencies (downstream services)
		Services struct {
			// Devices Status of a single dependency
			Devices DependencyCheck `json:"devices"`
		} `json:"services"`
	} `json:"checks"`

	// Status The overall health status of the service
	Status HealthStatus `json:"status"`

	// System System resource information
	System *SystemInfo `json:"system,omitempty"`

	// Timestamp Timestamp of the health check
	Timestamp time.Time `json:"timestamp"`

	// Uptime Service uptime information
	Uptime UptimeInfo `json:"uptime"`

	// Version Version information about the service
	Version VersionInfo `json:"version"`
}

// HealthStatus The overall health status of the service
type HealthStatus string

// Liveness Liveness probe response
type Liveness struct {
	// Status The liveness status of the service
	Status LivenessStatus `json:"status"`

	// Timestamp Timestamp of the liveness check
	Timestamp time.Time `json:"timestamp"`

	// Version Service version
	Version string `json:"version"`
}

// LivenessStatus The liveness status of the service
type LivenessStatus string

// MemoryInfo Memory usage information
type MemoryInfo struct {
	// AllocMb Current memory allocation in MB
	AllocMb *float32 `json:"allocMb,omitempty"`

	// GcCycles Number of completed GC cycles
	GcCycles *int `json:"gcCycles,omitempty"`

	// SysMb Total memory obtained from the OS in MB
	SysMb *float32 `json:"sysMb,omitempty"`

	// TotalAllocMb Total memory allocated since start in MB
	TotalAllocMb *float32 `json:"totalAllocMb,omitempty"`
}

// Meta Response metadata containing tracing information and API versioning.
// All successful responses include this field to support observability and debugging.
type Meta struct {
	// ApiVersion API version used to process this request
	ApiVersion MetaApiVersion `json:"apiVersion"`

	// RequestId Unique identifier for this specific request.
	// Matches the `Request-Id` response header.
	// Use this for correlating logs and debugging.
	RequestId openapi_types.UUID `json:"requestId"`

	// TraceId W3C Trace Context trace ID extracted from the traceparent header.
	// Present only when distributed tracing is enabled.
	// Use this to trace requests across multiple services.
	TraceId *string `json:"traceId,omitempty"`
}

// MetaApiVersion API version used to process this request
type MetaApiVersion string

// Pagination Pagination metadata for list responses
type Pagination struct {
	// HasNext Whether there is a next page
	HasNext *bool `json:"hasNext,omitempty"`

	// HasPrevious Whether there is a previous page
	HasPrevious *bool `json:"hasPrevious,omitempty"`

	// Links HATEOAS links for pagination navigation
	Links *PaginationLinks `json:"links,omitempty"`

	// NextCursor Opaque cursor for fetching the next page using keyset pagination.
	// Only present when hasNext is true.
	NextCursor *string `json:"nextCursor,omitempty"`

	// Page Current page number (1-indexed)
	Page int `json:"page"`

	// PreviousCursor Opaque cursor for fetching the previous page using keyset pagination.
	// Only present when hasPrevious is true.
	PreviousCursor *string `json:"previousCursor,omitempty"`

	// Size Number of items per page
	Size int `json:"size"`

	// TotalItems Total number of items across all pages
	TotalItems int `json:"totalItems"`

	// TotalPages Total number of pages
	TotalPages int `json:"totalPages"`
}

// PaginationLinks HATEOAS links for pagination navigation
type PaginationLinks struct {
	// First Link to the first page
	First *string `json:"first,omitempty"`

	// Last Link to the last page
	Last *string `json:"last,omitempty"`

	// Next Link to the next page (null if on last page)
	Next *string `json:"next"`

	// Previous Link to the previous page (null if on first page)
	Previous *string `json:"previous"`

	// Self Link to the current page
	Self *string `json:"self,omitempty"`
}

// PatchDevice Request body for partially updating a device (PATCH)
type PatchDevice struct {
	// Brand The brand/manufacturer of the device.
	// **Note:** Cannot be updated if the device state is "in-use"
	Brand *string `json:"brand,omitempty"`

	// Name The name of the device.
	// **Note:** Cannot be updated if the device state is "in-use"
	Name *string `json:"name,omitempty"`

	// State The current state of the device
	State *DeviceState `json:"state,omitempty"`
}

// PoolStats Connection pool statistics
type PoolStats struct {
	// Hits Number of successful pool hits
	Hits *int `json:"hits,omitempty"`

	// IdleConnections Number of idle connections in the pool
	IdleConnections *int `json:"idleConnections,omitempty"`

	// Misses Number of pool misses
	Misses *int `json:"misses,omitempty"`

	// StaleConnections Number of stale connections removed from the pool
	StaleConnections *int `json:"staleConnections,omitempty"`

	// Timeouts Number of connection timeouts
	Timeouts *int `json:"timeouts,omitempty"`

	// TotalConnections Total number of connections in the pool
	TotalConnections *int `json:"totalConnections,omitempty"`

	// WaitCount Number of times a connection was waited for
	WaitCount *int `json:"waitCount,omitempty"`

	// WaitDurationNs Total time spent waiting for connections in nanoseconds
	WaitDurationNs *int `json:"waitDurationNs,omitempty"`
}

// Readiness Readiness probe response with dependency status
type Readiness struct {
	// Checks Status of individual dependency checks grouped by category
	Checks struct {
		// Infra Infrastructure dependencies (storage, cache, etc.)
		Infra struct {
			Cache *CacheDependencyCheck `json:"cache,omitempty"`

			// Storage Status of a single dependency
			Storage DependencyCheck `json:"storage"`
		} `json:"infra"`

		// Services Service dependencies (downstream services)
		Services struct {
			// Devices Status of a single dependency
			Devices DependencyCheck `json:"devices"`
		} `json:"services"`
	} `json:"checks"`

	// Status The overall readiness status of the service
	Status ReadinessStatus `json:"status"`

	// Timestamp Timestamp of the readiness check
	Timestamp time.Time `json:"timestamp"`

	// Version Service version (optional)
	Version *string `json:"version,omitempty"`
}

// ReadinessStatus The overall readiness status of the service
type ReadinessStatus string

// SystemInfo System resource information
type SystemInfo struct {
	// CpuCores Number of CPU cores available
	CpuCores *int `json:"cpuCores,omitempty"`

	// Goroutines Number of active goroutines
	Goroutines *int `json:"goroutines,omitempty"`

	// Memory Memory usage information
	Memory *MemoryInfo `json:"memory,omitempty"`
}

// UpdateDevice Request body for fully updating a device (PUT)
type UpdateDevice struct {
	// Brand The brand/manufacturer of the device.
	// **Note:** Cannot be updated if the device state is "in-use"
	Brand string `json:"brand"`

	// Name The name of the device.
	// **Note:** Cannot be updated if the device state is "in-use"
	Name string `json:"name"`

	// State The current state of the device
	State DeviceState `json:"state"`
}

// UptimeInfo Service uptime information
type UptimeInfo struct {
	// Duration Human-readable uptime duration
	Duration string `json:"duration"`

	// DurationSeconds Uptime in seconds
	DurationSeconds *int `json:"durationSeconds,omitempty"`

	// StartedAt Timestamp when the service started
	StartedAt time.Time `json:"startedAt"`
}

// VersionInfo Version information about the service
type VersionInfo struct {
	// Api API version
	Api string `json:"api"`

	// Build Build version or commit hash
	Build string `json:"build"`

	// Go Go runtime version
	Go *string `json:"go,omitempty"`
}

// AcceptEncodingHeader defines model for AcceptEncodingHeader.
type AcceptEncodingHeader = string

// AcceptHeader defines model for AcceptHeader.
type AcceptHeader = string

// ApiVersionHeader defines model for ApiVersionHeader.
type ApiVersionHeader string

// AuthorizationHeader defines model for AuthorizationHeader.
type AuthorizationHeader = string

// BrandFilterParam defines model for BrandFilterParam.
type BrandFilterParam = []string

// CachePatternParam defines model for CachePatternParam.
type CachePatternParam = string

// CursorParam defines model for CursorParam.
type CursorParam = string

// DeviceIdParam defines model for DeviceIdParam.
type DeviceIdParam = openapi_types.UUID

// FieldsParam defines model for FieldsParam.
type FieldsParam = string

// IdempotencyKeyHeader defines model for IdempotencyKeyHeader.
type IdempotencyKeyHeader = openapi_types.UUID

// IfMatchHeader defines model for IfMatchHeader.
type IfMatchHeader = string

// IfNoneMatchHeader defines model for IfNoneMatchHeader.
type IfNoneMatchHeader = string

// PageParam defines model for PageParam.
type PageParam = int

// RequestIdHeader defines model for RequestIdHeader.
type RequestIdHeader = openapi_types.UUID

// SearchParam defines model for SearchParam.
type SearchParam = string

// SizeParam defines model for SizeParam.
type SizeParam = int

// SortParam defines model for SortParam.
type SortParam = []string

// StateFilterParam defines model for StateFilterParam.
type StateFilterParam = []DeviceState

// TraceparentHeader defines model for TraceparentHeader.
type TraceparentHeader = string

// TracestateHeader defines model for TracestateHeader.
type TracestateHeader = string

// BadRequest Standard error response format
type BadRequest = Error

// CacheBadRequest Error response for cache operations
type CacheBadRequest = CacheError

// CacheHealthOk Cache health status response
type CacheHealthOk = CacheHealth

// CacheHealthUnavailable Cache health status response
type CacheHealthUnavailable = CacheHealth

// CachePurgeAllDevices Response after purging cache entries
type CachePurgeAllDevices = CachePurge

// CachePurgeDevice Response after purging cache entries
type CachePurgeDevice = CachePurge

// CachePurgeLists Response after purging cache entries
type CachePurgeLists = CachePurge

// CachePurgePattern Response after purging cache entries by pattern
type CachePurgePattern = CachePatternPurge

// CacheServerError Error response for cache operations
type CacheServerError = CacheError

// CacheUnavailable Error response for cache operations
type CacheUnavailable = CacheError

// Conflict Standard error response format
type Conflict = Error

// DeviceCreated Response envelope containing a single device with metadata
type DeviceCreated = DeviceEnvelope

// DeviceRetrieved Response envelope containing a single device with metadata
type DeviceRetrieved = DeviceEnvelope

// DeviceUpdated Response envelope containing a single device with metadata
type DeviceUpdated = DeviceEnvelope

// DevicesList Response envelope containing a paginated list of devices with metadata
type DevicesList = DevicesListEnvelope

// HealthDown Comprehensive health check response with system metrics
type HealthDown = Health

// HealthOk Comprehensive health check response with system metrics
type HealthOk = Health

// LivenessDown Liveness probe response
type LivenessDown = Liveness

// LivenessOk Liveness probe response
type LivenessOk = Liveness

// NotAcceptable Standard error response format
type NotAcceptable = Error

// NotFound Standard error response format
type NotFound = Error

// PreconditionFailed Standard error response format
type PreconditionFailed = Error

// RateLimit Standard error response format
type RateLimit = Error

// ReadinessDown Readiness probe response with dependency status
type ReadinessDown = Readiness

// ReadinessOk Readiness probe response with dependency status
type ReadinessOk = Readiness

// ServerError Standard error response format
type ServerError = Error

// Unauthorized Standard error response format
type Unauthorized = Error

// UnprocessableEntity Standard error response format
type UnprocessableEntity = Error

// PurgeCacheByPatternParams defines parameters for PurgeCacheByPattern.
type PurgeCacheByPatternParams struct {
	// Pattern Glob-style pattern to match cache keys.
	// Examples: `device:*`, `devices:list:v1:*`
	Pattern CachePatternParam `form:"pattern" json:"pattern"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Purge all device caches
	// (DELETE /admin/cache/devices)
	PurgeAllDeviceCaches(w http.ResponseWriter, r *http.Request)
	// Purge all device list caches
	// (DELETE /admin/cache/devices/lists)
	PurgeDeviceListCaches(w http.ResponseWriter, r *http.Request)
	// Purge cache for a specific device
	// (DELETE /admin/cache/devices/{deviceId})
	PurgeDeviceCache(w http.ResponseWriter, r *http.Request, deviceId DeviceIdParam)
	// Check cache health status
	// (GET /admin/cache/health)
	GetCacheHealth(w http.ResponseWriter, r *http.Request)
	// Purge cache entries by pattern
	// (DELETE /admin/cache/pattern)
	PurgeCacheByPattern(w http.ResponseWriter, r *http.Request, params PurgeCacheByPatternParams)
	// Health check
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /liveness)
	LivenessCheck(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /readiness)
	ReadinessCheck(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Purge all device caches
// (DELETE /admin/cache/devices)
func (_ Unimplemented) PurgeAllDeviceCaches(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Purge all device list caches
// (DELETE /admin/cache/devices/lists)
func (_ Unimplemented) PurgeDeviceListCaches(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Purge cache for a specific device
// (DELETE /admin/cache/devices/{deviceId})
func (_ Unimplemented) PurgeDeviceCache(w http.ResponseWriter, r *http.Request, deviceId DeviceIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check cache health status
// (GET /admin/cache/health)
func (_ Unimplemented) GetCacheHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Purge cache entries by pattern
// (DELETE /admin/cache/pattern)
func (_ Unimplemented) PurgeCacheByPattern(w http.ResponseWriter, r *http.Request, params PurgeCacheByPatternParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /liveness)
func (_ Unimplemented) LivenessCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readiness probe
// (GET /readiness)
func (_ Unimplemented) ReadinessCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PurgeAllDeviceCaches operation middleware
func (siw *ServerInterfaceWrapper) PurgeAllDeviceCaches(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PurgeAllDeviceCaches(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PurgeDeviceListCaches operation middleware
func (siw *ServerInterfaceWrapper) PurgeDeviceListCaches(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PurgeDeviceListCaches(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PurgeDeviceCache operation middleware
func (siw *ServerInterfaceWrapper) PurgeDeviceCache(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "deviceId" -------------
	var deviceId DeviceIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "deviceId", chi.URLParam(r, "deviceId"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deviceId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PurgeDeviceCache(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCacheHealth operation middleware
func (siw *ServerInterfaceWrapper) GetCacheHealth(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCacheHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PurgeCacheByPattern operation middleware
func (siw *ServerInterfaceWrapper) PurgeCacheByPattern(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params PurgeCacheByPatternParams

	// ------------- Required query parameter "pattern" -------------

	if paramValue := r.URL.Query().Get("pattern"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pattern"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "pattern", r.URL.Query(), &params.Pattern)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pattern", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PurgeCacheByPattern(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LivenessCheck operation middleware
func (siw *ServerInterfaceWrapper) LivenessCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LivenessCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReadinessCheck operation middleware
func (siw *ServerInterfaceWrapper) ReadinessCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReadinessCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/admin/cache/devices", wrapper.PurgeAllDeviceCaches)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/admin/cache/devices/lists", wrapper.PurgeDeviceListCaches)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/admin/cache/devices/{deviceId}", wrapper.PurgeDeviceCache)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/cache/health", wrapper.GetCacheHealth)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/admin/cache/pattern", wrapper.PurgeCacheByPattern)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/liveness", wrapper.LivenessCheck)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readiness", wrapper.ReadinessCheck)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9C3PbuLU4/lUw6p2pnb+oSPIjiTqZjmIriVrLdmx50806fxsiIQkJCaoAaFub+rv/",
	"BgcACYqkHo6zzaa5M7friHidg4PzxsGXmh9Hs5gRJkWt86VG7nA0Cwn8PcKC+uoPkUQR5vNap3bACZYE",
	"YcTILQrIDfUJuqVyigIyxkkokZBYklq9doPDhMAgHLOg1ql1Z7NQfWA4IrVOjZ5OY0ZQaw+d8rh2f1+v",
	"+difkqspwaGcXsWfF+ZVHxEVSH+fuzOoKRNR69TsNxgNFhrkRzkmt+EcmU9m+e5IAZa4bM2mR1fWOrV2",
	"s73rNVtea2/YanZ2mp1m80OtXqOqfbP1or2zi/e8/dEz33sevCBec9xqezu7e/vPnr9o4pEf1Oq1kLLP",
	"gGBBwnGtU3uqVyKertX/vgKH9ZrGfaeGbzAN8QiWnsyC5Uu/r9ciosHGM/oL4YLGrNap3bRq9Ron/06I",
	"kH0F3N5ekzzfbTY90n4x8nZbwa6Hn7X2vd3d/f29vd3dZrPZrNVrkmOfQIcmHj/b32u9aO37we5OEDzf",
	"3X1ORu1Wy3/e3Gm98Gv3aqPMLuT2qXdHhaRs8uNuEWVeIpbtz25nd+/R96eV25/WaOn+BGZ/4luW351z",
	"wuHcU4FYLBEO6Q0pPY/QtV6TNCJC4mhWvTU3DliNZqMJR5hwHvOrEQ6uDJj5ZfTZDQ5pgOxHZwXQE7Cs",
	"mxhG1T9E45hHWDrDz7CUhDOYgvJFhnGqv6IZ5jgiknCUtiuZzoyF/p0QPnf6UJF1y2YWhN8QXkQt4UgP",
	"WDLDGNOQBEjGaJbwCUHAM50xE5ad/RL+CdvlMIfC+H5JMzX6OAnD/ICvkzCcI029CJcc1HX4Phrgu+Kh",
	"UBMaMbCU+BJWIgz8KfH1yaVszOHYaCQp3kEkpiF8nMVxeC6xlnlTqv7b2mvv7CouEZKDmDHiSxozUevs",
	"1WsRFUKJxN02LHahQVuTeJyoUZr1mowlDnMtWs167RZTeRAnTNY6rfZz/e/DhGPV5FhN04T/uzf9/0nm",
	"0LG9e1+vhVjIAwWYos+qMxRiSZg/H6huimcIgScKq2ckoAL5ej1AuOkBTWaKvQgZc2ia0UFAcYikP0Ot",
	"9jN1Hhutzt7uTrtjh6ExQ5yMEwHjbbq8pru8g7IR8yxEEYTQ+y70PqZ/bjp12516cnZ64EKkuNQopGJa",
	"xBIsYYGvibmQJAIKmyUHMVcrel6vTWIeJ5IySzARiWJFul9qOAxjfzCqdXb3Gnv12sQ/mPugarX29mE4",
	"9e1Zu7FjaKBr2ysyaDxXa1iDlyYz1QjwZMhLtZ3uNKPWnqjV01/PiR+zQNQ6L5qtPYCOlwii5vNOM1UU",
	"UjYNssgKoVFCQ5AnilI8PPJb7Z3dmkKEwnHcarT3NAIrdDvnSP880I98oDedaK/kaGqBcxoLOeHk/N0R",
	"au03WoUD8n0d0fjzzwP64AO6QosA0bumGuHHbEwnCV/YLpZXL0K6qNwdUSFRPEaWjgoWwG//a1ZaBu85",
	"jkTCJlUQ7yqSaO1tCDH5SoiJA/EbHOK7OTpv76KLUHK8gd3TfJFRcwbxmzieVG/xjrKW2ptu8fgrAR47",
	"AJ/SOxKi5wUbD/tS20al0Lrrvv/4XzTD67UZnlBmWNGX2hSLY3Ina50xDgWpq3+fcnJDY3V4zW8z4M+t",
	"ek3Q30mt07Zisi9JJGodyyFP8QT4J7CXJYIfjEiEWbDUwQNc/aHm5AxLf3qld8xdxYW2YWIWzpGcEmss",
	"QkNnEVX2C2rv7b955cxgtn+NKQq+sgLlpKMWDVMuKc5MsOBHdpUsP0Z7w5YrAh/tFO3kTtFOsPQUjbUA",
	"Bav8CofhlaMAZbvWDUO79yAihTbjg1Jix1WNs4mU3FyY4lD3UF/WmCOobJ1NYrwaZZqAbotGc2QbueRH",
	"QgIe2L16LR3DzNh54qoDfsVg2RoEZZOQXJX5Cs/hUw5TJRBvQtCL2MmNqdbECQ6U+iiuVjrHVNM52jIa",
	"OVLtt39aNz/dFf8Fd8VD5WZG7Uvkt6ZzGSPs+2QmkeR4PKb+T1L/acg/giH/UNI1+kKZMvajKUzlrvRq",
	"lWk/tTweUWVq51Smtr9UZVLarXE6BIQDQrq+T4Q4iJnkMThXbt/qj/o/mh6Fz+nMeE0OTs7OkR4AURZQ",
	"H0PY8HZK/Sl6Oxyemo8C+ZihEUGKYaMg4aqV0sSxLxMc2hhS45IpxRrFY/gIo884GYd0MlWyXMxiJgja",
	"ek2kP0XnErMA82C7can4q4mcK7pJ5DTm9HfgIHWk4CFMesP5jNTRmZ7K6wfqC+ckhGbw7+5p3zM7UEf9",
	"sTdQqj/8dRwzYv8JGJ5hTpg0/7CGhPCnJIKtlPOZWomQClI4CzncDvBdd0I2xOo0vkVhbBDHiUhCKRSq",
	"cA5HAJ1FNzD4oHHJflFnTAkKypDQfq1VaHy+v9tslsBEmSQTwjVQKcVWwdI97SPDG/Tmj2OO5BRElt7O",
	"3NYB1WdTEpZEtc5v6ueP9RKkghpscFqJTVAfA8oJmDHCrICkC2hcMg9dzzi9wZJcd9CZpTMqkJgRn46p",
	"rxi36pMIwqF5hO88PFHNB/iORkmEFJN00etOkd8PGIDFHvxLjZAItXMQK1V2KiR06PAkGpFxzNW8igJ0",
	"93TUBbI3ENSRWdvLHfBELCNKczR6zI8DyiaVKIyjGScCNhGHk5hTOY3c7XQgHcXBPLesye90Vrqp5kNA",
	"xqE+PiMOnJwwSeW8YsOzE9sPqpebNkJ6uDElXC+VY19h0pwTgbDPYyFQlISSzkKCrOxFW2bLZjy+oYE2",
	"jPyQEiZRzNGEMMJBjOl98gQNyHYO7nWtnRQvJjbeqSUJVV+K0PeGuHKPeoA1JPEEANVGkyEp2DcWoHgm",
	"aUSFpL5SBfyEc6UrqL/VAWpcsgtB9OG80fyCpVxQAZ3jgylnV7OJZCQURlnKgcQiU76s4dao7e8Eu2Rv",
	"vH9ZW0GZR1jIQRyonavc56FVS9DtlDBLhnHCfYJusUBKYUKRGSS3mPckqCvB/Q/MkJLKyOZ7oDeDYfmm",
	"qJPpQeCgbGeOYh/QXLXUi7O+lWoslwRlF5xb3mYaSTkNcVq60DMsyRGNqIT/qVqu5WksiUaEq5VnB0ap",
	"BSRAM8I1y7ulLIhv0dbZ6wO0v7/7HPlxNAspZjJ3HlorhUm6tDMSYcqW8KPj4rK47aOIVqFZU7fcaI0v",
	"9tZfoiCV2Ltg9A6lOjPaMhJh2yFTxeZDNZBdGlcDitVYfNbc22krc2jVSq3muGSR/05IqjBU8MmtGeGe",
	"aVNHOLzFc/FfYn5nRPJ5dywJX00WqQyOkbImrRTlagiaalA2byld9v4qrA4z1c9qCVWLeb9zgKC51j/v",
	"JNL9rGKnsBxQBd8oActQYzyPxaa3KnrgjZ7hYH/0rLX/ot3c2dlpec3WCtY6TFXWzWGAbi4IN4QFMfcy",
	"PQmagyXnQuLHbBK/lPst7r//PBn83luxxl8wn1etytgkSE6xRHg8Jr50FS1/qnZYiTtfazeIkUksqQ6v",
	"5OwE8JV4Vvupo5zhsHSFEBcw+WWp6TRbqUjpViSA013QqEpVU5OSdkvDUGlc8HmkTmykpDCAavsvilyl",
	"YNWR0a/qSKtXTCfqquWlluwCItawZGbVooMEFCPVa0tsG3cUHoWkDLYDzaPDuQ7NXOPZLKRakD79JGJ2",
	"DSp4MpvFXIIZc8n6Y/DrGnpTYtxkPsNhL47QgC6YoYSlA6EoXaPNDSRCqrE4kQlnAu0299FxLFE3Xf4i",
	"bhcnWo7aHEbNgssHKUH3RjaWjIFKHCtLW9ZoOeJuWorUUgSZ0UQH3bQWAAcLrRzUzHqugBf6rrLpcoew",
	"CuTT7nlveIJudtGIYK5UkfgzYQA2TuRUyTKN18Ylew2ipYNe6ZY3u41ZMgqp3/gyw/MwxsF944ugE4Zl",
	"wsn9AriFTmT+j5C87dIT2p8PDvvNo2H37mjYa/1y2JuffOreqv9/T/uiH4XT4KC/3//Uvx18eicHhz05",
	"GP5yMRh29weH6v9f4T69pf7OL7T/KaaDw97e4NOg+evwQh5H/Z1f583dD4dheDR8FQ2GfTn4/V3r+JO/",
	"ezJ8Nf01Ov7cZ81GuurKLVlgaFmWreQJcTcpixD9/ynIl5eNLQ31f8LYx+H25WWj8f/9XymVvuKYBa9p",
	"KAk/VYyxuGX6ozKjwL+3JbYb6CCOIuwJJVJBn1D7d3KWsrbGJevpneigv0Ovl+ATrJsUjPxe/WYchh/V",
	"b7MwDkgaLQfkQFpwhhvtZXRxQHXs/EstwndHhE3k1KitEWXpvwvA11VzE3ZvNdPPmHM8107kOVCS0nBq",
	"1mdhEpsrUPUmjEce9LOxOHVGASvGsPtM5iLDjuigaxvYu67bv0UnpEJ2blqdJ9cLVO1EActQk0UTqwmm",
	"xDZPuIirdv9khpW66UMb2GcFApHeCAtlTaQJEI1L9l6pydburoPQuJ7hCbnO53TTCYu5EQtPnlwIPCGd",
	"J08uWauBXlMuUlO0gw5j9leJKPPDJEjXsJUIItTEpLCG7UvWbqDzolHbQcpCvnZWy8id1IBfKxPZ/TQz",
	"ORv285jHEbI/Ok4ctfpXhJExlQLFN6DBjgWRzoIALg+da0lqfX/khjBtUyh9C/lTzCZEoBGRt4SwdNGq",
	"5yuidlQZbaBoM1+LiBDzidbWtPXBYnTy+vV5b4iEj5kyp7ZV74OYCSpAl1L4QoL+ToRe+HEsFdaRBlIg",
	"zAmK9V5r0hDIQ0EMsmeGuSAKS2CTQypGQWch839Eih0evT+ef3j/uvnh/dmr4KAv+uzXMpZ7e/Jp4LLc",
	"z6rv8fDi9sNw0hwcduWHYX/vV9psDt6/ax697+0Mhr/K48N37eNPF63jw3e3g8PurWLDHxSrjvZC8vYd",
	"Hb+rOBeacnI8w2EVe81mGWfUGQH9oOJgDKcEJdoWc2ww4yswEfCti4v+Ibp59iAbCwCZYTnN4AjMkpYe",
	"8NUW2WtKwkBUsnsSBuoUfzIRJxlbR5OJD4yhO1CM1rtIYI13R0dURHZoLreNyBTfUHV2WWy7pyxhGw7J",
	"mdHgiBAKmTi07ZSG2UHXNFAMUuFB/RdkgPoD7JprPdt7KqeF0XODp4lEqTZl2jeAP/gLUk2xYQNJpmLp",
	"DuZgq2UhD5nkkSI5bBnL27CwYFu7kBUUWTf1T/hdQ5V9iDBLxthXioJ2XmtoswbaqttKMyLrSMev1H91",
	"8o+eMA3Eqb5wFRE21no6oE0a8FJtjrCQ9pJKvhkE4VSTt91h76R7jhi+oRM9IHwz7AUUc7sbYs4kvgOc",
	"AR+GnztbIhnBX626/au9fQ38jenu8UgRoXDVCb2AzpYg4Xj7OlX8s50l4RgWkmNQ+oqmJa2FS3NlFJeF",
	"N2s0qKsdqsPu1HXI6L5eu6VyepRGJJ3bVVpYWfTooGVxNBin7gJjB029oxUjy+z70kXW012vZ8FMdfzL",
	"OKQGvVahWf6Gvd+73od6Z2v7Y4Ue2Q9INIshhv1PMl/hvPpMIOeBMJFwOC+6q0SnJ+dD1xPd1+xU4Eh3",
	"UmalaocnmDKItxjGMxwepc7C9i6axgkX2/VLpkkCLHFLKuBkzAdkEGVCEhwo9g1YA/McBYk28yw7O9M8",
	"NyJMWgYAIaARQVi77JFh+O4nwxVmhKMwnlAfhyieEZ0mAUJar0WRvV35gmzdRGAsWhLOvnj/JPOvlBz9",
	"McQQKmMZQzwxIQgFzsqwxTBz52lHCRxjkfg+UTJlnHMIpyECmAWUaiKcqMcagYtyDJlIyQrvSX98HDOy",
	"Cfh+zAKqPmWBcqHNWvSmN+wgK5V2mrvgtLBhEwt4CvAUC6UHaz0xMEOcXgyfnnaHB2876JQrjVIKw7GF",
	"GiDtTO6oUCpiIgi6rD25rG1/BaKyMNIKbJ3iCalQMNQnG6BQaMq0ZbTV8igLyB0J8s7zKmtnQsodFi0w",
	"/WiURK7h9w3c7JgFKCCjZDJR/5olfBYr42QD73vjkhVDB6An/cuD/AB6V9iwr+EHWRrFhm78c4K5P61S",
	"GpMw9LSjGZqZq7wmSKumBlSBdLIqF+gCwk2rGi+OAgH1HpuEVExRiNkkAStGkijSXgbFlV8TcKWkHNkw",
	"htuYB+gGc+0/FmiLNCaNOrqs8QQMpMtaykPgt8uaNpmwIB5lgjBBlQJllgJWHPylDLVYTsuB0itKrXuj",
	"JP793y91zpHSm7JJc3lIlzW1tsEc6V/VP4n0G7a/cZy4AxhngUaS+a4XYzvp+yT5SbM7JnpG8+8hHmVT",
	"KhgO4mik43K3Wq0OJeFFiC6TZrO9D/rGy1QNVTOm/zAAabXKdlYAQ0/HOaR6wR95yC5rgB1lYWhFOXcU",
	"9OAVZt+/qyy+9t5ezjnULiV4+nsVC8sCVuB6AtluuFG6tHazfFFw76OUa6kekQ7gZv6rZUzsPOZymRUH",
	"HmIRc5l6Hkbzct8dpFF4QMPQQZ+uU2A/ehuuPa2Zq2kICxRhxDwgPOd+NrYRbFRd02JdGyl1lGmjKFVH",
	"XTehmvall7WC87UFqx/Ns97osHd+AL4lTQ+oe36wvehPzIaxeF/Tt6imK9+c3KAf65nP0VGTvb9vqXH+",
	"A4D/B+D+T9rpPynU2yUatOuM3FvtizxXY6/ptYV1bOy1XTjSdWtQLqI6u423LooLOXcpKv+Pk3GtU/vL",
	"06y0zlPdTDzVFu+5tb4ybO2sxpYT/V0/Yro83Iu2TmaEDUlIIiL5HEQ3lnQUgkTPYhfXX0xI5t77AiFW",
	"jwb33he9GP23/nkc4om4v1YM0vTooDaakjsU0AlVCpxRIy5rzaaRVXbADtrJN23to9FcEgGt0rk6qLWf",
	"a/bcaeWsYnFioTZbway+bjvBvLyrVzgBT6vrmIJHOrjsa8wWtJkHB8tLFRwny7PKnG02vd+wN256Lz5+",
	"2WnfZ/9o7d97vzW9F9gbf/zSvi+3dLMw/DcJvzcu2UGJH0oJm89k/lKbFzNMeSFTqxCrr/P4U/yy2Rw3",
	"959h3BzhF8326NlSxK3OiL1Ps5tfxQHVnhXN5LzsmpGJ4Ovk6IVYaVWxrLLTbxs+1a0gwz1d2TJ2oett",
	"aaZh6yW5W2TUYMh61MZaZvZnJboK1rK9VvgwUPM3KZfC6zQtXpBco6dxU62Nr1PVawN0zfL3KI2/xHi9",
	"wSzdLkOeloEPw56tpbMUemi0Ptj6TsMGcI+TKpgvhiUQw2HRPiZD7IHnFGXaAHpTkunKfivWc/rH+cmx",
	"8bTmrg+BQK696h5enfXeXfTOhzX3fklJb6VqcwfwhfsMa1qfa9w92ajkmb6zRNnkymDtSnMmFxUD3SJ3",
	"cwClfG5dlJT0RpH18xUzP74D3KxN7z24+FdC6K9wYG9YIA/l/HJYoAiHSpciAdJuLYkpE8hWCUtpzr2R",
	"4uSUVKzJtH5ayJPJp4t7/WDVCGXJ5ZmPZ40BFr1B9/WcGrGid3VyoR1nKefODVOW3nefVnn0vp5/0GAl",
	"Dy3Wj7tPbyLn6r2tMUqh2wYiXEFcSbALVezQ1ggX69VBzNrwBLsCJ/BYS/Gqiyd4+qLmBljVHZbiYbE8",
	"54YIeAsdyzBQKO25CM1COZoNwFrouRS+kto3jw+iM7ra06yCXQozXDP3cBh6zs3LTXQzfU19pXZVKFSw",
	"IbCnaoAyWKtqHOhwiBCgeSzC+zA1dBNQ8xUEHgvYw2KFgKVwpgUbvhWYeoJHBq9YHmIpkE7BiG8Fplsh",
	"YhNATdZbFbz6nBImOSUiS3C2OXBLYTfBEFOSYCPQ0z5rCCJTNfSxxM/r8oKiFqg/hvUWa5c+FnhlZU8V",
	"cDEbh9TfVPfQzOOKsqtEKFYSElkokMbUZPqTZYNwT0BffdV3shcV+IOT49dH/YMF7b1kqI4dkgobTg7n",
	"2bjfhXWTR5I2lEuRZNJyGI7IUx17Suu9bYSytHbEb+nX/mBwMey+Oupdve73jg5rdZ0XUuvUTFWnAppH",
	"JC2kdDulWT2ZbA339TWGtzm9Dxn/Y0k3B0dKX4Dhv38i+Hoz7sAc0AUbzp5bE1Jzsyq0ZzLOZxz8tOW+",
	"qS2n6dBzSu1vwEydXsvtDtNufarSWkuP3ZAwni1V28wd2JxAf1yS0R6Y9GLTSqIpuw7/WLRn7wiv6r5w",
	"l9i9durB/64k3bI7vrlh0hu2aw+1eCd3YThB5AZDZXdnv/ZI/oJ15dhl3Zy7hN/vIU6rtX0pPyvm+7c8",
	"K4/BXn8S6p9LdqjGlTSnU/4el8rArDEVW1YSWbG6i8PUbdLN4uLP6e+uIpJVJVE6GgSq0RYdoze9Ibol",
	"XJckyqUJtqHY9LJr4I9yVnpDvJKqnYIfpiaGZ7M7V0qRYgGNH5SG45kpJvel6AqDUhURkdM4ECbvCEi7",
	"QkMF3mrJ04P+3tvs+1JqX1E7Ky0BtTD8QC/uIbW1LFyYk7QsB1wHwzBRVuhAw/pI1bXe9IZ1dHqh/qc7",
	"PHhbR4e9o96wV0dve93DOjo5HfZPjs/XqoaVomKA77zuhGyE41wNLTWkwkBp7aLSJIg8Bg323OJUFmcX",
	"Qt9LMoCliBKmzs4Mj2hI5RwFVPjxDeFzXcXjWXunhc7N5adnjd1G61ug0jkHnEhOyc3GlkDm/F1qCGzs",
	"ul3bDkgX/g21m8eTO9+HMfHfkR4/1bsf3Q5xSnZumpG0TvTAtMvXBl3axbb7BnzHegT/R/wPm7OMn+f9",
	"Rz/vosICPIjD0KguEZEY6gvYS9r/cwbhbvPFd2oRfhUND2OJQ89U3i6UJVAfnfp/+oJKGpJVuLQJ+dn9",
	"ur1V9dO+10NgH0DaQOTZLkuFFzTaVHKJIyrkMvG18DjTT/35pzD8KQwfhQ88wJUkkJ/Kyp/epAd6k07O",
	"hz/9Rw/1H22IvOyhQc8+n7OJs8h0WSeXM3uNZS3pV52/WfrocAbGt0i3fUii7WoA9KjIvK4BLy/eEKYo",
	"+VttxYZ7cGTWs2IXsnfHXRi+xT5stAFrrj5dOYull1Uo3TjDLi0oegUFRUsukpzZ0qJuyVEow2m7luRW",
	"HZ8Mr7oHB71TyHEqz7C6OD6/OD09ORv2Dq8GvcN+92r462nPyYRK645mOU0XpRVQO7m7KHdRuJAJ5eT/",
	"FCqn5iBpoPQCd+eHvd+SLwqbT49ajp6fuVDfVINTR3kcJ+xhwY8rFsurtHvhNT+1kfpr+Wl9fXJxfJg7",
	"a6YjpMn1D9Ff1yH4v+bm+WGOy2sFUOGkpHWFgpjokwLZBj9PyTc/JZETAiruVlo8ykNndosSZkpGIUGZ",
	"T/S7GumFKaeMFrjNviunw+Zm/ve2ZTNO0gJg3hiuC2x6vUHiyVVEBezRQs1C2DvzCXn551Ocl1MWmd7p",
	"We/g5Piwr6yNq9fd/lHvsFxP6Q27b64G/fNBd3jw1lFPnGJpGdM8tU/twLJSxmDqHi+Wb7MvzuXVlTOn",
	"2BkaEcJSMPLECx4zHP4ojPbUoRJkLpVolps+4GOM/6yZ2mPAL/kO2e4f7Av/3k49x5J4ofUzbnDYVccr",
	"6Lj47uJZ9uYMufMJCUpP9ll32Ls66g/6w6vevw56vcNeXrEpGaWBTkOChXleBeGxJBztN+0jLD/KERvG",
	"MRpgNrf324USkRk2Un7jIPdndu6fxIMNbwt58LjQ6t4LzxB9j9zDPhn8zdxKC09wr3+8zmzHNTxM5vHu",
	"gMwICwjzKcnd4IZ79xmo38L7lHt7+fGBrHq12bwB/MDrrAGWeIQFuUo7Owat+ZZ7ChiaFUVB/3jYOzvu",
	"Hl31zs5OznJSwMIgSTSLOeY0nLs7k0oEkAdQYznEEoqnfBd3JCmThDMclmGob77ZOmQPwE6XoYSRu5l+",
	"8hkGQLEPCmzwfaPm66Vkij7zbhU0RB5ahpOfRv83lQYJw+YZoI1NR1vtBV5XKi8XFXNE7mZQEUW3Kh6V",
	"i+PuxfDtyVn/w4Iy2c091WTecKJZRaBs7O+tdlQJQmzRKFwC1GMgJS1984NwiguHLBWDyIPtAKzIQGnX",
	"xvnxYzGL9+/few7opCT1II8YwCtBlOnSRItvGprHuzjBYfTyMk1swDO68snd749vzXjsq3MxColnXoV+",
	"GP9KV1PkX/riuj6dxVP6S/eof9gFN5eV82X1Do6h3VXv+GJw9Uv36MKNxNlSmNkJ11PaUnAxIyged9CS",
	"11eqQ3I6jzEtpea89wwiVnw/GpfeCCgLX7oP8OKFKR//tfvw+uRs0B06e+A8eJSh0f6YFeVzHt9YgvIU",
	"25ilkiqr6/+9YDwjhTIt95cSQnkYzs967y76Z73D1aU+oIqGK8jckh5m5456x2+Gb5dW9NC1Suye2cfO",
	"WlBDv9VsIn+KOfbhXdY/+bF5DBnrsFBknogv1mW8JWHomcqMo8ShcEEirERPhpafivq3EnjpbgNyIZx1",
	"aD0f84Mp8cFdgcPwZAznb3kicb6jOmlllZlS18oc+aqhDljP4jgEuQhv7qhdn/F4RrikNmZuuEDpoFkx",
	"attusb8a/1xiubJY+2naUGE5ljj8J5mL1cnqnwm8lZY90ZR/iL696zyJ0Cx9EsH8pB8OK/vlo41P9ixz",
	"XXjDByzcNA1Sp/oplKdvNhXxQpYNZfgY0t9GNh1TKcX6AVingHdJ1a2yCuRZDc7fzNwfC3AaKE1qW/mO",
	"59PaUqAfBh8dG0TlyzVWAOjHbEwniTaLCm8hmDy74qpNLDG/bpPJmhKMeafY5hsqhdT9e+HFAru2rMly",
	"hJu1VWI8VyuvAIFlHybaMks4vBzk5wrojeYoe8l18QhXlBvJniTJj2U7OKDu1bPnfiiT+7u15ceqXnMq",
	"ExYfwUxfup1iLZUSYTJqDXRVL9iuve1n8HpJSmlmv3XhvfRYlhCaqTuYQ+dam1t3XtK1CKze8IfvdGF7",
	"aXVRj/5hhmED2BY8l6Ywrat02iIJ8PlBb46ueAbqMbcIV9Q7/aoD6Fb9L1njmjX/83uiNdlS0odPT91n",
	"OvMPwOYA1o9c1zd9pNo+F1CcXVe3q5wv97xUft7F949aFTtNNnqVZWGfjB2h0Ve2WyVa0kLEJeXvOKNw",
	"22eZdoMD+/DeqdNEP3e44KRJWzpDl2lChdWvKxRlXl3LpcIvvN5hAzucjBUPLTt/IRYSsFUmA9KXQy1V",
	"QM6MEZZaT0wvOuQQma2iwvxJ+QI836DspfLFwTuTgxL+cKQ/VS+MMhTRMKRZ8oErr5aLp9RU/FK9u47f",
	"DeFRnMjFjUlZf4aMA70lus6r805da7/R2oQ5qsOa11Xy2DcKSzJT4ia+1VJnwrFORkjYZ6Z+zGkr0PbB",
	"fLKKQ3ZLyux8V8wwe4JrCfHD5SfnFW4lMW3Jwi0aRYnUUehHo/syqX1ReAtaH73HeRt8pZwO7cvEq7m3",
	"fsT4TyVp0ioUmxNCmL1sHVRSwG5nd28DClg4eLAjOelXT53JuTfkKs5leoW4Wqckpon1+GglJq8FgkvA",
	"FgEoSkv141o41xx2deuBarOICzM39K+GOH1HOw9u7g1ttwpY9uZ4AS5BwnGJ+KHss2LiRvQt8riMCky1",
	"JPF044PIqcfJmHDC/HISqYD9XJZGj4ZVNXqz82fEhmtq6wAE/GEiEDmpUe1WqNfuPDWg56xCq1JZNXJr",
	"iVDhvO6pdsVOCXO7zbIyyyOiSBQswy2ncrW/WOW57vxkLK9tFxx3dPsjeJBzXpN0VfcpmvOX8zc9WeaN",
	"Yucaae6N0pWnbGkdgFp9kycQa/fFBw/XP57KsrXPLa9+EyxtuexY54YsO+MVnjZ7tdgklbguNx1LyqNS",
	"BxwWBxlgf0oZ8TjBAey8Hgwau5RfEhMpyKFK96ijRurhTUv9kl9JDGKt7QS0HMJI5XtaodS+TSLMFgG2",
	"rV2Yq+MmNvpltrGACSeG8qB3sb+JSuNEadYQ+YVMpUfS9dJA0OpHH/Wbjjo6Wv6G6JjHEXKiGSbXf0El",
	"XBVwWqWPmMOQkUi2vS5WK4+uodESx5TUFxaKthVGqQlt8/C+8jRnlmth5AxVhZhmYftMeLJM2urXj8HH",
	"5mOQVCkd5SYxml3xAd+qA3uY/Utx/VvzRsMtj+3r2tJOX5hoIYFo+UbbIexKyna0MiAQRzNOpoQJJVFz",
	"pnnKmWGtYi4kiZTI42UxJugilvlyKAvoDQ2SnMtFTyXQhMfJTPtsfSzJJOZFRw9lY14iVfvqZyF5AsYn",
	"ymUfbwkZczwhde1r1A+dbxcXDyGEdV5OKQbqamaK1VJ8oWfBbNfDlG2e0Om7Zeg1ib15qIP4lgnJCY6Q",
	"7bpd4jdLx/yaddthPpYF4XLmEWyfA0wppEtcKfEN4TgMy6NAZlRHP44/5/0pxsMSYcokYVip6zklGdoX",
	"jVQg+1VIOodWfTaO15ZYZt3uiXs8aZXM4MvKV1BVK7vqm+WpAbaTyQvQvarCKBkGsnHTVdUtsygjgLQk",
	"RIn2rL+gGY9HpDpquYyEbOmLP4h4NiGEdGmPTArOtpazjmx/shlvWo1mo7l+2Kxsv8t2d0CimM+BdopK",
	"AHxDiXag59Il8xuMwzD2B6PqMHGkR4J2JjuVocGrXInAvYYbDh2HMZgeZsE6M0EteOIfzP2wjPM6gddY",
	"jakUvDcHyNfNc1X29lc5ssVclMGj0yQMNPFI6fAkQFp5nBJ0cl6E61m7sbMOXJCc0a1CZG5ig8b0Qq6Q",
	"mMvizK1me7fxfPXc96VkUWYup7Z5WtHSsc2tLp3TQVmAuqd9S9GUTRqXrBuGTpk9p5oTZX6YBEQrl0YJ",
	"jG39DxSPFFOwpZ7UyAEZJZOJHrRIk2nCVIkZmS1Je0JkjEyaly0+pZ9bzdjPTSvPXm5aDzPXCm5oV482",
	"3RuXDC4cEwFUdZ2laF1nKqA2UHR1LIMxUNBNkheboDCeiDI8fQOD8AGmGLmTkGToHJ+i/dW4ZKecCPUD",
	"RNjBqCwz4KhAhClDJXAxImMzH7cXTrHPYyFQlISSzsJUzhRe8P9qU8+17BxSLGPBpzk/0MKt9PRbdubU",
	"PoPzK3vQfJH4p1gck7sSl/z7KZFTAuEPrv2HiKltmS24LHSE1ix1FMchwQzqhWFxyskNjcvkecngM9O4",
	"MMEYh6J0hrXiJRlaspgJuZMHCRdlDq6TGVZnz4fP+vV44pRhTTGAErh/8pnMBZEoc6Y1LtmJIr+ZoUUg",
	"Q4NjBafC1iIFkfk/ov6nmB69P55/eP+6+eH92avgoC/67Fd6QvvzwWG/eTTs3h0Ne61fDnu3J58Gtyef",
	"urfvaV/0o/Cz6ns8vLj9MJw0B4dd+WHY3/uVNpuD9++aR+97O4Phr/L48F37+NNF6/jw3e3gsHvbp7f0",
	"w0F/vx/theTtOzp+V3ZaZ6W2sRXVgAeTCLjV8igLyN1CNd+WIz1bpVlKZtcfuB85otl0Tyx5PtK+zNWe",
	"fOW+3KX7wl7NP/zr14p9EfR3skyr0QWEZ4QXDlO7CaE+syMmertkf0DX6FvX6Dpliw3fVMaemlwUihYv",
	"V6dgwlPouHLCwvjPV+aauozX4AaQmYM0t4rlfHjtKFhGjssiYWPKhVwWCiMImhT2NQ2C/V19edm6TJrN",
	"9r4C7WW7uUHMS2erLF8BhGNXLOD5wxfASsWRu4CMC2+xJAwRHaOYZcvaXrKu9trrUiPrGFpOwjnMsVK6",
	"uWvNcyh3vdlGbn/VOlZFT7OY5LcimvvSIyL96dpZfTPMJcVhONcxRR3As0kX8F7Ptk54dXPDWo+Y6NK4",
	"ZE+eHMeSdJ48QcV3bKnb1sR2qUCXJoB6WVsQHX9A3uAjrziXD4IG+O4Pyj4sEo57YaHwUq5Nt1t1bWJK",
	"5VK737EqYShon5NU7Z3dVbKKBiHJ1rR0PtXUqQOR3phQk2+WN0eFWO7SAHhMM9dr0l7pyZB4bXigbQ4g",
	"TqL4xrXRFkFbOb+kEYkTucJfk5JA2tyZYz31YimMi0rGGpvWWjntLaay4vGHDDZwxCHswggXxjCVOjk/",
	"N2f7+TqTHiY6jfu4ElI1KxIzUIwxBdar3QM5sBlmcVmaZxP+b9MrPvVaVrWlRDiYTwvOYh3KKsv+/BnN",
	"+hnN+q9Es9KSRd9hTCJb238pKIG29AsPONx+tPjEkuCTE8YrrkzHv9NylssiFP4sOYj5chF7cHqBfNUI",
	"ld6Ze77Kqp7EPE6k2p1ls5hMOafxRuJchwBWp5ilUZ1SRn0B+uTaijy8hlOqxF8Mt2s/FfY/v8JeeV3I",
	"jvexlIrSaHUl29AR5qVnMzDazMoEOzNW2j7H/KY7zai1J0rTCU2Hc6PqFGMzdpGoRBt60WztraFk8/WT",
	"4I0gQaZXFRNvPu80mw9Pfs/WlGGgdBvd/IHC8s3Hils7mUgsBN+WRt1qq0Npo4SW5Ye9Uj+nwghU2sgU",
	"D53mRgV55OGR32rv7JZNMCmB9k2MeMKAGMpWOolbjfbeSswr6C0ApWqLIH7CqZyfQyUiwNgrLKjfTcoS",
	"wuCTfi1noTKW4s04UKQppNrgG4IIC2YxZWBA6UJHtU5tpEbIlj2Vcqa9OYLI2E46grpHry2hnXbPe8OT",
	"WqFMMvyMtk5DLBVFeN0Ji5W1js4NUGgYfyZMbKObXV16q3HJughAJnXNAkMItEJZLk1VGpIccI1LptfS",
	"QaYi081uY5aMQuo3vszwPIxxcN/4IuiEYSVJ7oGTZiBDn0WYdSEdTecQuvbhxGqGb/PTIWJtXuKo1WsJ",
	"D01/0Xn6dELlNBk1/Dh6irk/pZIotZ1bn1utUECki85650MYUwEZYYbh+vHC3QeTv64kLTo4uzh0qhxA",
	"DHdMQ0m4vrds3juiELa8ZH/5CzKp+IexUj3Vbz3sT9NLvSbZuHPJPPTkST948qSDiuHo9BqUbnaMI6Ia",
	"2gcccET0h1dKLjhfXGmuLxPodiBcVLuD3OWJrSVVmszUcHlY0bfinWqEtW6UGVS8SoRWkM+SkAj1o4fS",
	"AeFkF646qCYKXEC0vg6RsbNi8wWhDvcfkBLmzEN9gCh72GzxCoVZpKKGX9KcCPXjcEo14SWCOFVjssQJ",
	"WJzJhXAC2E4D4AFkQonaaTXNX+wc6Fx/mmv8XpwdoVMsp84SFJavn960nl6jrRmnEeZz8zSX2RNdZWWx",
	"h1PApoNuWte2RPoWDqGIpdnU/GL6mShRY3fDshwQd+jrkmfX1Aa4KRxqJNM8uzSsH13QD7IFsZ9EhEn9",
	"lBg40OFrGE9U31ec4M9wvEwfw9BRhD/FPJ2KMp8TNYwFSm3ZIZlxYlgyPDz2fO/F7vYlew9vvzE3Awbp",
	"C7/QnAR1hHPA39IwtBiA03rtDN2BcOY1UkQGaDDpIZbj54eG3ucJE0R20GXSbO74injhLxgkfSBNCRZP",
	"fcsOl1owrAUcNeABhPGOKPtsR0t4qAf7G+IkfHlZM87XmHsG1suamufirJ8Zr7MQ+4A+NYUme5Lmsgg0",
	"JeEM+SFVqiqK6EQRLZIxYuSWpHsg0IiMY06QAOgsC7Tip3iYjMjS8iYvZAxLdFsIRdgrpRvySiRafuyF",
	"dSHz/KD6uZzkhb2GY9UDixdNCv/y7Pufw/mMeCf6ZlgHsVgwOh5fm0avOY6cr4e941/tp3+dn3unPJba",
	"A9hBrb+hKA7Iy1EY+591o3PJqS+9IcdMKE7j2eV3UITvPDwhL3daezv7zWbzb3bh58lICx6hx7DLtF29",
	"0zik/ryDAjLGSSg9wX30V0HC8V91hzMyJpwTnjYUehUxpxPKPEWWHsSfzS+61ynhUEs0ZiLt6OOIcPxy",
	"a7uOIurzeKasKfjnhMQ29/Dl1vY1KAsh9QkTxNEABv1hQeLHM8LMU4Qxnzw1ncRT1Ra8NzJcVB7eYElu",
	"8dxJvTT6qOqgxgP9uLbTaDZ2dImTKSiBT0GZewruwqeO/0wLjzJDXZ1NHZaHToEVSpAopPdH5+Q5vlG9",
	"TiVOIItI1/xomFPjchOo3xygWDMFW/JZa5wIcvK2zJZ20PPm8xfmdcVUc4EqbVCUpRuGGj/g5NTF4Wzu",
	"UudLrd1sVhmsaTuNFQ9Kk3g4DD1H49pttlb3zxXxva/X9tafNFdKHLrurNvVrXLkqv5QgMxR+n/7eP+x",
	"7pQXBLShQmkWpdDiiVBWRldtQ+2jGrSMbuDl5AdSD9DFvxPCtYrZX6QeWydGyVW47jkeQ3WGb0tE9oay",
	"kI9ERRpD/yP045z1DYjoiy3xeb8OJVkqslmKixfhR3NEpUD9wz+CUA5MFbIZVhIRqllWFf3LmhjHWD84",
	"VT9B+cuvo7EgvSq8u37XEQ48m4L8J6E0XU3LbHpWtMd4h1aR2zS9Czchsoy+ZMKZyKW9VFeeQyIZ6UtC",
	"34zM3hDpFvV7OJFk7+8+nA3tbDjZQzca4nMGxflneFdvcK5u3ZriKK2cB8+XmcIamrRIYAvJNS7ZuTWK",
	"J2E88oSch2kpPIG2SGPSqKNrW+3uOv1bdBRL7Dy53v623AgI5dX8NKsjuBFDypUyfCSmZHfjf4QrlVZz",
	"LKNYR+XebJNKqvOu7FMsp7uyi1NDd8NOYKTaPh8dWBck/FcJy/qPiKcVomnJbW2T2WKu5pvb2m4cJbPP",
	"dGSrwIdm+jlHLfgEjkrKpCEsnKSAUSKtVS4uWVZ8b+GueAMZNwAJ9CohQFB0wBcYmpZ3Byb1YHMm9AeJ",
	"O/dx/k2Yxtv81V/LInSigeERoXMdtpQizmk0CxdvjyIZK1IgPKIsLUYonHesEmZux10InaYUc6WqS45l",
	"zAXaCulngv6ZjAhnRBKxXTqg8fQTjsQ0TsJA++9MILBsP+0N3ofvqPt0vdrT9ovVfZynGdfd0TD3yv/C",
	"nub2MH8puWoXuZuptsbBXsi7Wbmd5c+SNS7Zgc5HAyWHU3XWwnxyVcYU7Ctk+g5fMeWqklgKi9Ozu0QR",
	"J6aYItyTo0xIzHxSRiJp4t7DaST3wtw3JJKFR/uWUclCOmIpmSwyDjdcajgH6DVaVC4k6sd6Y6GEFTi8",
	"dduCdxHPaMOIYvXfp1+Mx/AenpPgVCk+gOlcghYonjZ0XkxTcQMOMjZVwdybrAq4wlVDHgeJTlBdY61+",
	"HP1xa/2Ybk9FSWaIqurAQq46fD6wW1LE3+SQWfZSzw56HY6dEehAJM6AhkjuP97/vwAAAP//2jba534E",
	"AQA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
