// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: device/v1/device.proto

package devicev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceState int32

const (
	DeviceState_DEVICE_STATE_UNSPECIFIED DeviceState = 0
	DeviceState_DEVICE_STATE_AVAILABLE   DeviceState = 1
	DeviceState_DEVICE_STATE_IN_USE      DeviceState = 2
	DeviceState_DEVICE_STATE_INACTIVE    DeviceState = 3
)

// Enum value maps for DeviceState.
var (
	DeviceState_name = map[int32]string{
		0: "DEVICE_STATE_UNSPECIFIED",
		1: "DEVICE_STATE_AVAILABLE",
		2: "DEVICE_STATE_IN_USE",
		3: "DEVICE_STATE_INACTIVE",
	}
	DeviceState_value = map[string]int32{
		"DEVICE_STATE_UNSPECIFIED": 0,
		"DEVICE_STATE_AVAILABLE":   1,
		"DEVICE_STATE_IN_USE":      2,
		"DEVICE_STATE_INACTIVE":    3,
	}
)

func (x DeviceState) Enum() *DeviceState {
	p := new(DeviceState)
	*p = x
	return p
}

func (x DeviceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceState) Descriptor() protoreflect.EnumDescriptor {
	return file_device_v1_device_proto_enumTypes[0].Descriptor()
}

func (DeviceState) Type() protoreflect.EnumType {
	return &file_device_v1_device_proto_enumTypes[0]
}

func (x DeviceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceState.Descriptor instead.
func (DeviceState) EnumDescriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_SERVING_STATUS_UNKNOWN         HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING_STATUS_SERVING         HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_SERVING_STATUS_NOT_SERVING     HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVING_STATUS_SERVICE_UNKNOWN HealthCheckResponse_ServingStatus = 3
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "SERVING_STATUS_UNKNOWN",
		1: "SERVING_STATUS_SERVING",
		2: "SERVING_STATUS_NOT_SERVING",
		3: "SERVING_STATUS_SERVICE_UNKNOWN",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"SERVING_STATUS_UNKNOWN":         0,
		"SERVING_STATUS_SERVING":         1,
		"SERVING_STATUS_NOT_SERVING":     2,
		"SERVING_STATUS_SERVICE_UNKNOWN": 3,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_device_v1_device_proto_enumTypes[1].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_device_v1_device_proto_enumTypes[1]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{14, 0}
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Brand         string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	State         DeviceState            `protobuf:"varint,4,opt,name=state,proto3,enum=device.v1.DeviceState" json:"state,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_device_v1_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Device) GetState() DeviceState {
	if x != nil {
		return x.State
	}
	return DeviceState_DEVICE_STATE_UNSPECIFIED
}

func (x *Device) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Device) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Brand         string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	State         DeviceState            `protobuf:"varint,3,opt,name=state,proto3,enum=device.v1.DeviceState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeviceRequest) Reset() {
	*x = CreateDeviceRequest{}
	mi := &file_device_v1_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceRequest) ProtoMessage() {}

func (x *CreateDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceRequest.ProtoReflect.Descriptor instead.
func (*CreateDeviceRequest) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDeviceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDeviceRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateDeviceRequest) GetState() DeviceState {
	if x != nil {
		return x.State
	}
	return DeviceState_DEVICE_STATE_UNSPECIFIED
}

type CreateDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeviceResponse) Reset() {
	*x = CreateDeviceResponse{}
	mi := &file_device_v1_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceResponse) ProtoMessage() {}

func (x *CreateDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceResponse.ProtoReflect.Descriptor instead.
func (*CreateDeviceResponse) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDeviceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type GetDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceRequest) Reset() {
	*x = GetDeviceRequest{}
	mi := &file_device_v1_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceRequest) ProtoMessage() {}

func (x *GetDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceRequest) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeviceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceResponse) Reset() {
	*x = GetDeviceResponse{}
	mi := &file_device_v1_device_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceResponse) ProtoMessage() {}

func (x *GetDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceResponse) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeviceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type ListDevicesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by brand(s). Multiple values use OR logic.
	Brands []string `protobuf:"bytes,1,rep,name=brands,proto3" json:"brands,omitempty"`
	// Optional filter by state(s). Multiple values use OR logic.
	States []DeviceState `protobuf:"varint,2,rep,packed,name=states,proto3,enum=device.v1.DeviceState" json:"states,omitempty"`
	// Page number (1-based).
	Page uint32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// Page size.
	Size uint32 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// Sort fields (e.g., "-createdAt", "name"). Prefix with `-` for descending.
	Sort          []string `protobuf:"bytes,5,rep,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_device_v1_device_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{5}
}

func (x *ListDevicesRequest) GetBrands() []string {
	if x != nil {
		return x.Brands
	}
	return nil
}

func (x *ListDevicesRequest) GetStates() []DeviceState {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *ListDevicesRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDevicesRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListDevicesRequest) GetSort() []string {
	if x != nil {
		return x.Sort
	}
	return nil
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_device_v1_device_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{6}
}

func (x *ListDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *ListDevicesResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	TotalItems    uint32                 `protobuf:"varint,3,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	TotalPages    uint32                 `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	HasNext       bool                   `protobuf:"varint,5,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	HasPrevious   bool                   `protobuf:"varint,6,opt,name=has_previous,json=hasPrevious,proto3" json:"has_previous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_device_v1_device_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{7}
}

func (x *Pagination) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Pagination) GetTotalItems() uint32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *Pagination) GetTotalPages() uint32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *Pagination) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *Pagination) GetHasPrevious() bool {
	if x != nil {
		return x.HasPrevious
	}
	return false
}

type UpdateDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Brand         string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	State         DeviceState            `protobuf:"varint,4,opt,name=state,proto3,enum=device.v1.DeviceState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceRequest) Reset() {
	*x = UpdateDeviceRequest{}
	mi := &file_device_v1_device_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceRequest) ProtoMessage() {}

func (x *UpdateDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeviceRequest) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDeviceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDeviceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDeviceRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *UpdateDeviceRequest) GetState() DeviceState {
	if x != nil {
		return x.State
	}
	return DeviceState_DEVICE_STATE_UNSPECIFIED
}

type UpdateDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceResponse) Reset() {
	*x = UpdateDeviceResponse{}
	mi := &file_device_v1_device_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceResponse) ProtoMessage() {}

func (x *UpdateDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeviceResponse) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateDeviceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type PatchDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Brand         *string                `protobuf:"bytes,3,opt,name=brand,proto3,oneof" json:"brand,omitempty"`
	State         *DeviceState           `protobuf:"varint,4,opt,name=state,proto3,enum=device.v1.DeviceState,oneof" json:"state,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,5,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchDeviceRequest) Reset() {
	*x = PatchDeviceRequest{}
	mi := &file_device_v1_device_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchDeviceRequest) ProtoMessage() {}

func (x *PatchDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchDeviceRequest.ProtoReflect.Descriptor instead.
func (*PatchDeviceRequest) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{10}
}

func (x *PatchDeviceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PatchDeviceRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PatchDeviceRequest) GetBrand() string {
	if x != nil && x.Brand != nil {
		return *x.Brand
	}
	return ""
}

func (x *PatchDeviceRequest) GetState() DeviceState {
	if x != nil && x.State != nil {
		return *x.State
	}
	return DeviceState_DEVICE_STATE_UNSPECIFIED
}

func (x *PatchDeviceRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type PatchDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchDeviceResponse) Reset() {
	*x = PatchDeviceResponse{}
	mi := &file_device_v1_device_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchDeviceResponse) ProtoMessage() {}

func (x *PatchDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchDeviceResponse.ProtoReflect.Descriptor instead.
func (*PatchDeviceResponse) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{11}
}

func (x *PatchDeviceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type DeleteDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceRequest) Reset() {
	*x = DeleteDeviceRequest{}
	mi := &file_device_v1_device_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceRequest) ProtoMessage() {}

func (x *DeleteDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeviceRequest) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteDeviceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_device_v1_device_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{13}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=device.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_device_v1_device_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{14}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_SERVING_STATUS_UNKNOWN
}

var File_device_v1_device_proto protoreflect.FileDescriptor

const file_device_v1_device_proto_rawDesc = "" +
	"\n" +
	"\x16device/v1/device.proto\x12\tdevice.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe6\x01\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12,\n" +
	"\x05state\x18\x04 \x01(\x0e2\x16.device.v1.DeviceStateR\x05state\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x91\x01\n" +
	"\x13CreateDeviceRequest\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12 \n" +
	"\x05brand\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x05brand\x128\n" +
	"\x05state\x18\x03 \x01(\x0e2\x16.device.v1.DeviceStateB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x05state\"A\n" +
	"\x14CreateDeviceResponse\x12)\n" +
	"\x06device\x18\x01 \x01(\v2\x11.device.v1.DeviceR\x06device\",\n" +
	"\x10GetDeviceRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\">\n" +
	"\x11GetDeviceResponse\x12)\n" +
	"\x06device\x18\x01 \x01(\v2\x11.device.v1.DeviceR\x06device\"\xe1\x01\n" +
	"\x12ListDevicesRequest\x12(\n" +
	"\x06brands\x18\x01 \x03(\tB\x10\xbaH\r\x92\x01\n" +
	"\x10\n" +
	"\"\x06r\x04\x10\x01\x18dR\x06brands\x12?\n" +
	"\x06states\x18\x02 \x03(\x0e2\x16.device.v1.DeviceStateB\x0f\xbaH\f\x92\x01\t\x10\x03\"\x05\x82\x01\x02\x10\x01R\x06states\x12\x1b\n" +
	"\x04page\x18\x03 \x01(\rB\a\xbaH\x04*\x02(\x01R\x04page\x12\x1d\n" +
	"\x04size\x18\x04 \x01(\rB\t\xbaH\x06*\x04\x18d(\x01R\x04size\x12$\n" +
	"\x04sort\x18\x05 \x03(\tB\x10\xbaH\r\x92\x01\n" +
	"\x10\x05\"\x06r\x04\x10\x01\x182R\x04sort\"y\n" +
	"\x13ListDevicesResponse\x12+\n" +
	"\adevices\x18\x01 \x03(\v2\x11.device.v1.DeviceR\adevices\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.device.v1.PaginationR\n" +
	"pagination\"\xb4\x01\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x1f\n" +
	"\vtotal_items\x18\x03 \x01(\rR\n" +
	"totalItems\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\rR\n" +
	"totalPages\x12\x19\n" +
	"\bhas_next\x18\x05 \x01(\bR\ahasNext\x12!\n" +
	"\fhas_previous\x18\x06 \x01(\bR\vhasPrevious\"\xab\x01\n" +
	"\x13UpdateDeviceRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12 \n" +
	"\x05brand\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x05brand\x128\n" +
	"\x05state\x18\x04 \x01(\x0e2\x16.device.v1.DeviceStateB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x05state\"A\n" +
	"\x14UpdateDeviceResponse\x12)\n" +
	"\x06device\x18\x01 \x01(\v2\x11.device.v1.DeviceR\x06device\"\x93\x02\n" +
	"\x12PatchDeviceRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12#\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\x00R\x04name\x88\x01\x01\x12%\n" +
	"\x05brand\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\x01R\x05brand\x88\x01\x01\x12=\n" +
	"\x05state\x18\x04 \x01(\x0e2\x16.device.v1.DeviceStateB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00H\x02R\x05state\x88\x01\x01\x12;\n" +
	"\vupdate_mask\x18\x05 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMaskB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_brandB\b\n" +
	"\x06_state\"@\n" +
	"\x13PatchDeviceResponse\x12)\n" +
	"\x06device\x18\x01 \x01(\v2\x11.device.v1.DeviceR\x06device\"/\n" +
	"\x13DeleteDeviceRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xe9\x01\n" +
	"\x13HealthCheckResponse\x12D\n" +
	"\x06status\x18\x01 \x01(\x0e2,.device.v1.HealthCheckResponse.ServingStatusR\x06status\"\x8b\x01\n" +
	"\rServingStatus\x12\x1a\n" +
	"\x16SERVING_STATUS_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16SERVING_STATUS_SERVING\x10\x01\x12\x1e\n" +
	"\x1aSERVING_STATUS_NOT_SERVING\x10\x02\x12\"\n" +
	"\x1eSERVING_STATUS_SERVICE_UNKNOWN\x10\x03*{\n" +
	"\vDeviceState\x12\x1c\n" +
	"\x18DEVICE_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DEVICE_STATE_AVAILABLE\x10\x01\x12\x17\n" +
	"\x13DEVICE_STATE_IN_USE\x10\x02\x12\x19\n" +
	"\x15DEVICE_STATE_INACTIVE\x10\x032\xdd\x03\n" +
	"\rDeviceService\x12O\n" +
	"\fCreateDevice\x12\x1e.device.v1.CreateDeviceRequest\x1a\x1f.device.v1.CreateDeviceResponse\x12F\n" +
	"\tGetDevice\x12\x1b.device.v1.GetDeviceRequest\x1a\x1c.device.v1.GetDeviceResponse\x12L\n" +
	"\vListDevices\x12\x1d.device.v1.ListDevicesRequest\x1a\x1e.device.v1.ListDevicesResponse\x12O\n" +
	"\fUpdateDevice\x12\x1e.device.v1.UpdateDeviceRequest\x1a\x1f.device.v1.UpdateDeviceResponse\x12L\n" +
	"\vPatchDevice\x12\x1d.device.v1.PatchDeviceRequest\x1a\x1e.device.v1.PatchDeviceResponse\x12F\n" +
	"\fDeleteDevice\x12\x1e.device.v1.DeleteDeviceRequest\x1a\x16.google.protobuf.Empty2\xa1\x01\n" +
	"\rHealthService\x12F\n" +
	"\x05Check\x12\x1d.device.v1.HealthCheckRequest\x1a\x1e.device.v1.HealthCheckResponse\x12H\n" +
	"\x05Watch\x12\x1d.device.v1.HealthCheckRequest\x1a\x1e.device.v1.HealthCheckResponse0\x01B\x9f\x01\n" +
	"\rcom.device.v1B\vDeviceProtoP\x01Z<github.com/architeacher/devices/pkg/proto/device/v1;devicev1\xa2\x02\x03DXX\xaa\x02\tDevice.V1\xca\x02\tDevice\\V1\xe2\x02\x15Device\\V1\\GPBMetadata\xea\x02\n" +
	"Device::V1b\x06proto3"

var (
	file_device_v1_device_proto_rawDescOnce sync.Once
	file_device_v1_device_proto_rawDescData []byte
)

func file_device_v1_device_proto_rawDescGZIP() []byte {
	file_device_v1_device_proto_rawDescOnce.Do(func() {
		file_device_v1_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_device_v1_device_proto_rawDesc), len(file_device_v1_device_proto_rawDesc)))
	})
	return file_device_v1_device_proto_rawDescData
}

var file_device_v1_device_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_device_v1_device_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_device_v1_device_proto_goTypes = []any{
	(DeviceState)(0),                       // 0: device.v1.DeviceState
	(HealthCheckResponse_ServingStatus)(0), // 1: device.v1.HealthCheckResponse.ServingStatus
	(*Device)(nil),                         // 2: device.v1.Device
	(*CreateDeviceRequest)(nil),            // 3: device.v1.CreateDeviceRequest
	(*CreateDeviceResponse)(nil),           // 4: device.v1.CreateDeviceResponse
	(*GetDeviceRequest)(nil),               // 5: device.v1.GetDeviceRequest
	(*GetDeviceResponse)(nil),              // 6: device.v1.GetDeviceResponse
	(*ListDevicesRequest)(nil),             // 7: device.v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),            // 8: device.v1.ListDevicesResponse
	(*Pagination)(nil),                     // 9: device.v1.Pagination
	(*UpdateDeviceRequest)(nil),            // 10: device.v1.UpdateDeviceRequest
	(*UpdateDeviceResponse)(nil),           // 11: device.v1.UpdateDeviceResponse
	(*PatchDeviceRequest)(nil),             // 12: device.v1.PatchDeviceRequest
	(*PatchDeviceResponse)(nil),            // 13: device.v1.PatchDeviceResponse
	(*DeleteDeviceRequest)(nil),            // 14: device.v1.DeleteDeviceRequest
	(*HealthCheckRequest)(nil),             // 15: device.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 16: device.v1.HealthCheckResponse
	(*timestamppb.Timestamp)(nil),          // 17: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),          // 18: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),                  // 19: google.protobuf.Empty
}
var file_device_v1_device_proto_depIdxs = []int32{
	0,  // 0: device.v1.Device.state:type_name -> device.v1.DeviceState
	17, // 1: device.v1.Device.created_at:type_name -> google.protobuf.Timestamp
	17, // 2: device.v1.Device.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: device.v1.CreateDeviceRequest.state:type_name -> device.v1.DeviceState
	2,  // 4: device.v1.CreateDeviceResponse.device:type_name -> device.v1.Device
	2,  // 5: device.v1.GetDeviceResponse.device:type_name -> device.v1.Device
	0,  // 6: device.v1.ListDevicesRequest.states:type_name -> device.v1.DeviceState
	2,  // 7: device.v1.ListDevicesResponse.devices:type_name -> device.v1.Device
	9,  // 8: device.v1.ListDevicesResponse.pagination:type_name -> device.v1.Pagination
	0,  // 9: device.v1.UpdateDeviceRequest.state:type_name -> device.v1.DeviceState
	2,  // 10: device.v1.UpdateDeviceResponse.device:type_name -> device.v1.Device
	0,  // 11: device.v1.PatchDeviceRequest.state:type_name -> device.v1.DeviceState
	18, // 12: device.v1.PatchDeviceRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 13: device.v1.PatchDeviceResponse.device:type_name -> device.v1.Device
	1,  // 14: device.v1.HealthCheckResponse.status:type_name -> device.v1.HealthCheckResponse.ServingStatus
	3,  // 15: device.v1.DeviceService.CreateDevice:input_type -> device.v1.CreateDeviceRequest
	5,  // 16: device.v1.DeviceService.GetDevice:input_type -> device.v1.GetDeviceRequest
	7,  // 17: device.v1.DeviceService.ListDevices:input_type -> device.v1.ListDevicesRequest
	10, // 18: device.v1.DeviceService.UpdateDevice:input_type -> device.v1.UpdateDeviceRequest
	12, // 19: device.v1.DeviceService.PatchDevice:input_type -> device.v1.PatchDeviceRequest
	14, // 20: device.v1.DeviceService.DeleteDevice:input_type -> device.v1.DeleteDeviceRequest
	15, // 21: device.v1.HealthService.Check:input_type -> device.v1.HealthCheckRequest
	15, // 22: device.v1.HealthService.Watch:input_type -> device.v1.HealthCheckRequest
	4,  // 23: device.v1.DeviceService.CreateDevice:output_type -> device.v1.CreateDeviceResponse
	6,  // 24: device.v1.DeviceService.GetDevice:output_type -> device.v1.GetDeviceResponse
	8,  // 25: device.v1.DeviceService.ListDevices:output_type -> device.v1.ListDevicesResponse
	11, // 26: device.v1.DeviceService.UpdateDevice:output_type -> device.v1.UpdateDeviceResponse
	13, // 27: device.v1.DeviceService.PatchDevice:output_type -> device.v1.PatchDeviceResponse
	19, // 28: device.v1.DeviceService.DeleteDevice:output_type -> google.protobuf.Empty
	16, // 29: device.v1.HealthService.Check:output_type -> device.v1.HealthCheckResponse
	16, // 30: device.v1.HealthService.Watch:output_type -> device.v1.HealthCheckResponse
	23, // [23:31] is the sub-list for method output_type
	15, // [15:23] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_device_v1_device_proto_init() }
func file_device_v1_device_proto_init() {
	if File_device_v1_device_proto != nil {
		return
	}
	file_device_v1_device_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_device_v1_device_proto_rawDesc), len(file_device_v1_device_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_device_v1_device_proto_goTypes,
		DependencyIndexes: file_device_v1_device_proto_depIdxs,
		EnumInfos:         file_device_v1_device_proto_enumTypes,
		MessageInfos:      file_device_v1_device_proto_msgTypes,
	}.Build()
	File_device_v1_device_proto = out.File
	file_device_v1_device_proto_goTypes = nil
	file_device_v1_device_proto_depIdxs = nil
}
